AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Upload → Lambda → S3 (use an existing bucket)

Parameters:
  BucketName:
    Type: String
    Default: 13052025-sachin
    Description: Name of the existing S3 bucket for uploads

Globals:
  Function:
    Runtime: python3.13
    Handler: app.handler
    Timeout: 15
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        BUCKET_NAME: !Ref BucketName

Resources:
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /upload
            Method: POST
            PayloadFormatVersion: '2.0'

  ListImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: list_images.handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName
      Events:
        ListImagesApi:
          Type: HttpApi
          Properties:
            Path: /list-images
            Method: GET

Outputs:
  ApiUrl:
    Description: Invoke URL
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'

  BucketName:
    Description: The S3 bucket used for uploads
    Value: !Ref BucketName
